### ISSUE TITLE
Error loading the model on CPU

### ISSUE THREAD

**Issue by leelasd** [isayevlab/AIMNet2#2]
Hi, 

When I try to run the model on Mac CPU, I am getting the following errors. Here is the command I used 

`python aimnet2_ase_opt.py ../models/aimnet2_wb97m-d3_0.jpt test.xyz out.xyz --charge 0 --traj trj.xyz`

The error is as below 
```bash
Loading AIMNet2 model from file ../models/aimnet2_wb97m-d3_0.jpt
Traceback (most recent call last):
  File "aimnet2_ase_opt.py", line 74, in <module>
    model = torch.jit.load(args.model, map_location=device)
  File "/opt/anaconda3/envs/delfta/lib/python3.7/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: [enforce fail at inline_container.cc:222] . file not found: wb97m_gas_0/version
```

I am using PyTorch 1.8.0

**Comment by zubatyuk** [comment]
You have to switch to a recent PyTorch 2.x version.

**Comment by leelasd** [comment]
Thank you so much for the advice ! That worked :)
